=== yearn/ydaemon/data/risks/_config/schema/risks.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "risks.json",
  "title": "Risk Framework",
  "description": "Risk framework scores for Yearn strategies",
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    },
    "codeReviewScore": {
      "type": "number"
    },
    "testingScore": {
      "type": "number"
    },
    "auditScore": {
      "type": "number"
    },
    "protocolSafetyScore": {
      "type": "number"
    },
    "complexityScore": {
      "type": "number"
    },
    "teamKnowledgeScore": {
      "type": "number"
    },
    "criteria": {
      "type": "object",
      "required": ["nameLike", "strategies", "exclude"],
      "properties": {
        "nameLike": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "strategies": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "address"
          }
        },
        "exclude": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": ["label", "criteria"]
}

=== yearn/ydaemon/data/risks/networks/1/strategystethaccumulator_v2.json
{
	"$schema": "risks",
	"label": "stETH accumulator v2",
	"codeReviewScore": 3,
	"testingScore": 3,
	"auditScore": 5,
	"protocolSafetyScore": 2,
	"complexityScore": 1,
	"teamKnowledgeScore": 2,
	"criteria": {
		"nameLike": [
			"StrategystETHAccumulator_v2"
		],
		"strategies": [],
		"exclude": [
			"StrategystETHAccumulator"
		]
	}
}

=== yearn/ydaemon/data/risks/networks/250/tohedgilspookyjoint.json
{
	"$schema": "risks",
	"label": "IL-Hedge Hedgil V2 Spooky Liquidity Provider",
	"codeReviewScore": 3,
	"testingScore": 2,
	"auditScore": 5,
	"protocolSafetyScore": 3,
	"complexityScore": 4,
	"teamKnowledgeScore": 2,
	"criteria": {
		"nameLike": [
			"ToHedgilSpookyJoint"
		],
		"strategies": [],
		"exclude": []
	}
}

=== yearn/ydaemon/data/risks/networks/1/stargate.json
{
	"$schema": "risks",
	"label": "Stargate",
	"codeReviewScore": 2,
	"testingScore": 4,
	"auditScore": 5,
	"protocolSafetyScore": 4,
	"complexityScore": 4,
	"teamKnowledgeScore": 3,
	"criteria": {
		"nameLike": [
			"stargate"
		],
		"strategies": [
			"0x2b982BE433093A80e1801A0Dd894994a170a5025"
		],
		"exclude": []
	}
}

=== yearn/ydaemon/data/risks/networks/250/geistlenderborrower.json
{
	"$schema": "risks",
	"label": "Geist Lender Borrower",
	"codeReviewScore": 2,
	"testingScore": 2,
	"auditScore": 5,
	"protocolSafetyScore": 3,
	"complexityScore": 4,
	"teamKnowledgeScore": 2,
	"criteria": {
		"nameLike": [
			"GeistMIMLender",
			"GeistDAILender",
			"GeistfUSDTLender",
			"GeistUSDCLender",
			"GeistWFTMLender"
		],
		"strategies": [],
		"exclude": []
	}
}

=== yearn/ydaemon/data/risks/networks/1/st-ycrv.json
{
	"$schema": "risks",
	"label": "Staked Yearn CRV",
	"codeReviewScore": 3,
	"testingScore": 3,
	"auditScore": 2,
	"protocolSafetyScore": 1,
	"complexityScore": 3,
	"teamKnowledgeScore": 2,
	"criteria": {
		"nameLike": ["StYCRV"],
		"strategies": [
			"0x23724D764d8b3d26852BA20d3Bc2578093d2B022",
			"0xE7863292dd8eE5d215eC6D75ac00911D06E59B2d",
			"0xAf73A48E1d7e8300C91fFB74b8f5e721fBFC5873"
		],
		"exclude": []
	}
}

=== yearn/ydaemon/data/risks/networks/1/makerv3.json
{
    "$schema": "risks",
    "label": "Maker V3",
    "codeReviewScore": 3,
    "testingScore": 2,
    "auditScore": 5,
    "protocolSafetyScore": 1,
    "complexityScore": 4,
    "teamKnowledgeScore": 2,
    "criteria": {
        "nameLike": [
            "makerv3"
        ],
        "strategies": [],
        "exclude": []
    }
}

=== yearn/ydaemon/data/risks/networks/1/others.json
{
	"$schema": "risks",
	"label": "Others",
	"codeReviewScore": 5,
	"testingScore": 5,
	"auditScore": 5,
	"protocolSafetyScore": 5,
	"complexityScore": 5,
	"teamKnowledgeScore": 5,
	"criteria": {
		"nameLike": [
			"IBLevComp"
		],
		"strategies": [],
		"exclude": [
			"1INCHGovernance",
			"88MPH",
			"SSBv3",
			"SingleSidedBalancer",
			"SingleSidedBoostedBalancer",
			"StkAaveCooldown",
			"StrategyLiquityStabilityPoolLUSD",
			"StrategyNotionalLP",
			"StrategyNotionalLending",
			"StrategyTokemak",
			"StrategyYearnVECRV",
			"ToHegicSushiJoint",
			"WETHSingleSided",
			"aave",
			"accumulator",
			"ah",
			"ah2",
			"borrower",
			"convex",
			"crv",
			"curve",
			"genericlender",
			"genericlevaave",
			"genericlevcomp",
			"genlevaave",
			"genlevcomp",
			"idle",
			"inverse",
			"kashi",
			"maker",
			"makerv2",
			"pooltogether",
			"rook",
			"router",
			"singlesided",
			"snx",
			"snxstaking",
			"ssc",
			"stargate",
			"strategyangle",
			"strategylender",
			"stratmm",
			"synthetix",
			"vesper",
			"xsushi-staker",
			"NoHedgeUniV3StablesJoint",
			"strategygoldfinch",
			"auto-compounding aura",
			"maker-lev",
			"convextempledao-u"
		]
	}
}

=== yearn/ydaemon/data/risks/networks/1/convex-factory.json
{
	"$schema": "risks",
	"label": "Convex Factory",
	"codeReviewScore": 2,
	"testingScore": 3,
	"auditScore": 4,
	"protocolSafetyScore": 2,
	"complexityScore": 2,
	"teamKnowledgeScore": 1,
	"criteria": {
		"nameLike": [
            "strategyconvexfactory"
		],
		"strategies": [],
		"exclude": [
            "convex",
            "strategyconvexfraxfactory"
		]
	}
}
