=== yearn/ydaemon/data/meta/_config/schema/protocol.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "protocol.json",
  "title": "Protocol",
  "description": "A DeFi protocol",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "protocolVersion": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    }
  },
  "required": ["name", "description", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/protocols/250/Tarot.json
{
  "$schema": "protocol",
  "name": "Tarot",
  "protocolVersion": ["1"],
  "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming.",
  "localization": {
    "en": {
      "name": "Tarot",
      "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming."
    },
    "fr": {
      "name": "Tarot",
      "description": "Tarot est un protocole de prêt décentralisé sur le réseau Fantom. Il s'agit d'un protocole de prêt décentralisé sur lequel les utilisateurs peuvent prêter ou emprunter grâce à des pools isolées, ce qui permet aux emprunteurs de tirer parti de leurs jetons LP pour réaliser du yield farming avec effet de levier."
    },
    "es": {
      "name": "Tarot",
      "description": "Tarot es un protocolo descentralizado de préstamos en la red Fantom. Es un protocolo de préstamos en el que los usuarios pueden prestar o pedir prestado en pools aislados que les permite aprovechar sus tokens LP para apalancar su rendimiento."
    },
    "de": {
      "name": "Tarot",
      "description": "Tarot ist ein dezentrales Kreditprotokoll im Fantom-Netzwerk. Es ist ein dezentralisiertes Kreditprotokoll, bei dem Nutzer in isolierten Pools leihen oder verleihen können, was es Kreditnehmern ermöglicht, ihre LP-Token für Leverage Yield Farming zu nutzen."
    },
    "pt": {
      "name": "Tarot",
      "description": "Tarot é um protocolo de empréstimo descentralizado na rede Fantom. É um protocolo descentralizado de empréstimo onde os usuários podem emprestar ou tomar emprestado em pools isolados, o que permite que os tomadores de empréstimo alavanquem seus tokens LP para realizar farming alavancada de rendimentos."
    },
    "el": {
      "name": "Tarot",
      "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming."
    },
    "tr": {
      "name": "Tarot",
      "description": "Tarot, Fantom ağındaki merkezi olmayan bir borç verme protokolüdür. Kullanıcıların izole havuzlarda ödünç verebildiği veya ödünç alabildiği ve borçluların kaldıraç verimi çiftçiliği için LP jetonlarından yararlanmalarını sağlayan merkezi olmayan bir borç verme protokolüdür."
    },
    "vi": {
      "name": "Tarot",
      "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming."
    },
    "zh": {
      "name": "Tarot",
      "description": "Tarot 是个在 Fantom 网络上的去中心化借贷协议。其去中心化借贷协议让用户可以在独立的池中借出或借入资产，从而使得借款人能够应用他们的 LP 代币做杠杆挖矿。"
    },
    "hi": {
      "name": "Tarot",
      "description": "Tarot, Fantom नेटवर्क पर एक विकेन्द्रीकृत उधार प्रोटोकॉल है। यह एक विकेन्द्रीकृत उधार प्रोटोकॉल है जहां उपयोगकर्ता अलग-अलग पूल में उधार दे सकते हैं या उधार ले सकते हैं जो उधारकर्ताओं को लीवरेज उपज खेती के लिए अपने LP टोकन का लाभ उठाने में सक्षम बनाता है।"
    },
    "ja": {
      "name": "Tarot",
      "description": "TarotはFantomネットワーク上の分散型レンディングプロトコルです。分離されたプールでトークンの貸し借りができる分散型レンディングプロトコルであり、借り手はLPトークンを活用してレバレッジイールドファーミングを行うことができます。"
    },
    "id": {
      "name": "Tarot",
      "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming."
    },
    "ru": {
      "name": "Tarot",
      "description": "Tarot is a decentralized lending protocol on the Fantom network. It's a decentralized lending protocol where users can lend or borrow in isolated pools which enables borrowers to leverage their LP tokens for leveraged yield farming."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/1/InverseFinance.json
{
  "$schema": "protocol",
  "name": "Inverse Finance",
  "protocolVersion": ["1"],
  "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token.",
  "localization": {
    "en": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    },
    "fr": {
      "name": "Inverse Finance",
      "description": "Inverse Finance est une suite d'outils financiers décentralisés sans autorisation régis par legal Inverse DAO. Leurs principaux produits sont Anchor : un marché monétaire et DOLA : un stablecoin et un Vaults DCA (Dollar Cost Average). Les utilisateurs peuvent participer à la gouvernance du protocole par le biais du jeton natif INV."
    },
    "es": {
      "name": "Inverse Finance",
      "description": "Inverse Finance es un conjunto de herramientas financieras descentralizadas sin permiso gobernadas por Inverse DAO. Sus principales productos son Anchor: un mercado monetario, DOLA: moneda estable y vaults de promedio de coste en dólares. Los usuarios pueden opinar en Inverse DAO con su tokennativo INV."
    },
    "de": {
      "name": "Inverse Finance",
      "description": "Inverse Finance ist eine Reihe von erlaubnisfreien dezentralisierten Finanzwerkzeugen, die von der Inverse DAO verwaltet werden. Ihre wichtigsten Produkte sind Anchor: ein Geldmarkt, DOLA: Stablecoin, und Dollar Cost Averaging Vaults. Die Nutzer bekommen mit ihrem nativen INV-Token ein Mitspracherecht bei Inverse DAO."
    },
    "pt": {
      "name": "Inverse Finance",
      "description": "Inverse Finance é um conjunto de ferramentas financeiras descentralizadas e sem permissão governada pela Inverse DAO. Seus principais produtos são Anchor: um mercado monetário, DOLA: stablecoin, e Vaults de Custo Médio em Dólar. Usuários podem ter voz na Inverse DAO com o token nativo INV."
    },
    "el": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    },
    "tr": {
      "name": "Inverse Finance",
      "description": "Inverse Finance, Invers DAO tarafından yönetilen, izinsiz merkezi olmayan finans araçları paketidir. Başlıca ürünleri Anchor: para piyasası, DOLA: stablecoin ve Dolar Maliyet Ortalama Vault'udur. Kullanıcılar, yerel INV belirteci ile Inverse DAO'da söz sahibi olabilir."
    },
    "vi": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    },
    "zh": {
      "name": "Inverse Finance",
      "description": "Inverse Finance 是一套无需许可的去中心化金融工具，由 Inverse DAO 管理。主要产品有，Anchor: 金融市场，DOLA: 稳定币，以及“定期定额投资法”机枪池。Inverse DAO 是由 INV 的持有者来管理的。"
    },
    "hi": {
      "name": "Inverse Finance",
      "description": "Inverse Finance Inverse DAO द्वारा शासित अनुमति रहित विकेंद्रीकृत वित्त उपकरणों का एक सूट है। उनके मुख्य उत्पाद हैं Anchor: एक मुद्रा बाजार, DOLA: स्थिर मुद्रा, और Dollar Cost Averaging Vaults। उपयोगकर्ता अपने मूल INV टोकन के साथ Inverse DAO में अपनी बात रख सकते हैं।"
    },
    "ja": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    },
    "id": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    },
    "ru": {
      "name": "Inverse Finance",
      "description": "Inverse Finance is a suite of permissionless decentralized finance tools governed by Inverse DAO. Their main products are Anchor: a money market, DOLA: stablecoin, and Dollar Cost Averaging Vaults. Users can have a say in Inverse DAO with its native INV token."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/250/SolidexFinance.json
{
  "$schema": "protocol",
  "name": "Solidex Finance",
  "protocolVersion": ["1"],
  "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token.",
  "localization": {
    "en": {
      "name": "Solidex Finance",
      "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token."
    },
    "fr": {
      "name": "Solidex Finance",
      "description": "Solidex Finance est une plate-forme conçue pour augmenter les récompenses pour les stakers de jetons SOLID et les fournisseurs de liquidité sur Solidly \u2013 le tout avec une interface simple et facile à utiliser. Solidex Finance vise à simplifier le staking et la fourniture de liquidités avec son jeton SEX générateur d'intéret."
    },
    "es": {
      "name": "Solidex Finance",
      "description": "Solidex Finance es una plataforma creada para aumentar las recompensas para los participantes de SOLID y los proveedores de liquidez de Solidly - todo en una interfaz simple y fácil de usar. Solidex Finance tiene como objetivo simplificar el staking y la provisión de liquidez con su token SEX nativo que genera comisiones."
    },
    "de": {
      "name": "Solidex Finance",
      "description": "Solidex Finance ist eine Plattform, die die Belohnungen für SOLID-Staker und Solidly-Liquiditätsanbieter - über eine einfache und leicht zu bedienende Schnittstelle erhöht. Solidex Finance zielt darauf ab, das Staking und die Bereitstellung von Liquidität mit seinem gebührenpflichtigen SEX-Token zu vereinfachen."
    },
    "pt": {
      "name": "Solidex Finance",
      "description": "Solidex Finance é uma plataforma construída para impulsionar recompensas para os stakers de SOLID e provedores de liquidez da plataforma Solidly - numa forma simples e com interface fácil de usar. Solidex Finance procura simplificar o processo de fornecimento de liquidez e staking com seu token nativo, recebedor de rendimentos, chamado SEX."
    },
    "el": {
      "name": "Solidex Finance",
      "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token."
    },
    "tr": {
      "name": "Solidex Finance",
      "description": "Solidex Finance, tümü basit ve kullanımı kolay bir arayüzde SOLID stake edenlerin ve Solidly likidite sağlayıcılarının ödüllerini artırmak için oluşturulmuş bir platformdur. Solidex Finance, yerel ücretli SEX belirteci ile stake ve likidite sağlamayı basitleştirmeyi amaçlıyor."
    },
    "vi": {
      "name": "Solidex Finance",
      "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token."
    },
    "zh": {
      "name": "Solidex Finance",
      "description": "Solidex Finance 是个平台，提供简单易用的用户界面，主要目的是提升 SOLID 质押者和 Solidly 流动性提供者的奖励。 Solidex Finance 旨在通过其原生可赚取费用的 SEX 代币来为用户简化质押和流动性提供过程。"
    },
    "hi": {
      "name": "Solidex Finance",
      "description": "Solidex Finance, SOLID स्टेकर्स और Solidly लिक्विडिटी प्रोवाइडर्स के लिए पुरस्कार को बढ़ावा देने के लिए बनाया गया एक प्लेटफॉर्म है - सभी एक सरल और उपयोग में आसान इंटरफेस में। Solidex Finance का लक्ष्य अपने मूल शुल्क-अर्जित SEX टोकन के साथ हिस्सेदारी और तरलता प्रावधान को सरल बनाना है।"
    },
    "ja": {
      "name": "Solidex Finance",
      "description": "Solidex FinanceはSOLIDステーカーとSolidly流動性プロバイダーすべての報酬を高めるために構築されたプラットフォームであり、シンプルで使いやすいインターフェースを備えています。Solidex Financeは、そのネイティブな手数料稼ぐSEXトークンによりステーキングと流動性提供を簡素化することを目的としています。"
    },
    "id": {
      "name": "Solidex Finance",
      "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token."
    },
    "ru": {
      "name": "Solidex Finance",
      "description": "Solidex Finance is a platform built to boost rewards for SOLID stakers and Solidly liquidity providers - all in a simple and easy to use interface. Solidex Finance aims to simplify staking and liquidity provision with its native fee-earning SEX token."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/10/HopExchange.json
{
  "$schema": "protocol",
  "name": "Hop Exchange",
  "protocolVersion": ["1"],
  "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token.",
  "localization": {
    "en": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "fr": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "es": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "de": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "pt": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "el": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "tr": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "vi": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "zh": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "hi": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "ja": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "id": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    },
    "ru": {
      "name": "Hop Exchange",
      "description": "Hop Exchange is a scalable rollup-to-rollup general token bridge and Automated Market Maker. Users can have a say in protocol governance with its native HOP token."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/250/EsterFinance.json
{
  "$schema": "protocol",
  "name": "Ester Finance",
  "protocolVersion": ["1"],
  "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns.",
  "localization": {
    "en": {
      "name": "Ester Finance",
      "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns."
    },
    "fr": {
      "name": "Ester Finance",
      "description": "Ester Finance est un agrégateur de rendement. Il aide les utilisateurs à générer des intérêts là où les stratégies sont les plus intéréssantes."
    },
    "es": {
      "name": "Ester Finance",
      "description": "Ester Finance es un agregador de rendimiento. Ayuda a los usuarios a ganar intereses donde la estrategia optimiza los rendimientos."
    },
    "de": {
      "name": "Ester Finance",
      "description": "Ester Finance ist ein Renditeaggregator. Es hilft den Nutzern, dort Zinsen zu verdienen, wo Strategien die Rendite optimieren."
    },
    "pt": {
      "name": "Ester Finance",
      "description": "Ester Finance é um agregador de rendimento. Ajuda os usuários a receber rendimentos enquanto as estratégias otimizam os retornos."
    },
    "el": {
      "name": "Ester Finance",
      "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns."
    },
    "tr": {
      "name": "Ester Finance",
      "description": "Ester Finance bir getiri toplayıcıdır. Stratejilerin getirileri optimize ettiği durumlarda kullanıcıların faiz kazanmalarına yardımcı olur."
    },
    "vi": {
      "name": "Ester Finance",
      "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns."
    },
    "zh": {
      "name": "Ester Finance",
      "description": "Ester Finance 是个收益聚合器。他们的策略旨在为用户赚取最优化的收益。"
    },
    "hi": {
      "name": "Ester Finance",
      "description": "Ester Finance एक यील्ड एग्रीगेटर है। यह उपयोगकर्ताओं को ब्याज अर्जित करने में मदद करता है जहां रणनीतियाँ रिटर्न का अनुकूलन करती हैं।"
    },
    "ja": {
      "name": "Ester Finance",
      "description": "Ester Financeはイールドアグリゲーターです。利回りを最適化するストラテジーにより、ユーザーが利息を得ることを支援します。"
    },
    "id": {
      "name": "Ester Finance",
      "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns."
    },
    "ru": {
      "name": "Ester Finance",
      "description": "Ester Finance is a yield aggregator. It helps users to earn interest where strategies optimize the returns."
    }
  }
}
