=== yearn/ydaemon/data/meta/_config/schema/protocol.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "protocol.json",
  "title": "Protocol",
  "description": "A DeFi protocol",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "protocolVersion": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    }
  },
  "required": ["name", "description", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/protocols/250/IronBank.json
{
  "$schema": "protocol",
  "name": "Iron Bank",
  "protocolVersion": ["1"],
  "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted.",
  "localization": {
    "en": {
      "name": "Iron Bank",
      "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted."
    },
    "fr": {
      "name": "Iron Bank",
      "description": "L'Iron Bank est un protocole de prêt décentralisé pour les particuliers, les institutions et les protocoles d'accès aux services financiers. Developpé par Cream en collaboration avec Yearn Finance, il s'agit d'un protocole agnostique sans autorisation, open source sur Ethereum et Fantom. Les utilisateurs peuvent déposer leurs actifs dans l'Iron Bank pour générer un rendement, similaire à un compte d'épargne traditionnel. La différence entre l'Iron Bank et le protocole Cream v1 est que, sur l'Iron Bank, les protocoles de confiance peuvent contracter un prêt sans garantie lorsqu'ils sont sur la liste blanche (whitelisted)."
    },
    "es": {
      "name": "Iron Bank",
      "description": "Iron Bank es un protocolo descentralizado de préstamos para individuos, instituciones y protocolos para acceder a servicios financieros. Creado por C.R.E.A.M. Finance en colaboración con Yearn Finance, es un protocolo agnóstico a cualquier blockchain, de código abierto y que no requiere de ninguna autorización que opera en Ethereum y Fantom. Los usuarios pueden depositar sus activos en Iron Bank para obtener rendimiento, similar a una cuenta de ahorros tradicional. La diferencia entre Iron Bank y C.R.E.A.M. v1 es que en Iron Bank, los protocolos confiables pueden obtener un préstamo con garantía cero cuando están en la whitelist."
    },
    "de": {
      "name": "Iron Bank",
      "description": "Iron Bank ist ein dezentralisiertes Kreditprotokoll, das Einzelpersonen, Institutionen und Protokollen den Zugang zu Finanzdienstleistungen ermöglicht. Es wurde von Cream in Zusammenarbeit mit Yearn Finance entwickelt und ist ein erlaubnisfreies, quelloffenes und blockchain-agnostisches Protokoll, das Benutzern auf Ethereum und Fantom dient. Nutzer können ihr Vermögen auf Iron Bank hinterlegen, um eine Rendite zu erzielen, ähnlich wie bei einem traditionellen Sparkonto. Der Unterschied zwischen Iron Bank und Cream v1 besteht darin, dass in Iron Bank vertrauenswürdige Protokolle einen Kredit ohne Sicherheiten aufnehmen können, wenn sie auf der Whitelist stehen."
    },
    "pt": {
      "name": "Iron Bank",
      "description": "Iron Bank é um protocolo de empréstimo descentralizado para que indivíduos, instituições e protocolo acessem serviços financeiros. Construído por C.R.E.A.M. Finance em colaboração com Yearn Finance, é um protocolo código aberto e blockchain agnóstico, servindo usuários nas redes Ethereum e Fantom. Os usuários podem depositar seus ativos no Iron Bank para receber rendimentos, de forma similar a uma conta poupança tradicional. A diferença entre o Iron Bank e C.R.E.A.M. v1 é que os protocolos validados pelo Iron Bank podem obter empréstimos sem necessidade de garantia."
    },
    "el": {
      "name": "Iron Bank",
      "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted."
    },
    "tr": {
      "name": "Iron Bank",
      "description": "Iron Bank, finansal hizmetlere erişmek için bireyler, kurumlar ve protokoller için merkezi olmayan bir borç verme protokolüdür. C.R.E.A.M. Finance tarafından Yearn Finance ile işbirliği içinde oluşturulmuş, Ethereum ve Fantom'da kullanıcılara hizmet veren izinsiz, açık kaynaklı ve blok zinciri agnostik bir protokoldür. Kullanıcılar, geleneksel bir tasarruf hesabına benzer şekilde getiri elde etmek için varlıklarını Iron Bank'a yatırabilirler. Iron Bank ve C.R.E.A.M. v1 arasındaki fark, Iron Bank'ta güvenilir protokollerin beyaz listeye alındığında sıfır teminatlı kredi alabilmesidir."
    },
    "vi": {
      "name": "Iron Bank",
      "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted."
    },
    "zh": {
      "name": "Iron Bank",
      "description": "Iron Bank 是个去中心化的借贷协议，主要目的是提供金融服务给个人、机构和协议。它是由 C.R.E.A.M. Finance 和 Yearn Finance 合作打造的。它是一种无需许可，开源而且无特定区块链的协议，为以太坊和 Fantom 上的用户提供服务。用户可以将资产存入 Iron Bank 以赚取收益，就像传统的储蓄账户一样。Iron Bank 和第一版本的 C.R.E.A.M. 之间的区别在于，在 Iron Bank 上，已经被列入白名单的协议可以做零抵押的贷款。"
    },
    "hi": {
      "name": "Iron Bank",
      "description": "Iron Bank वित्तीय सेवाओं तक पहुँचने के लिए व्यक्तियों, संस्थानों और प्रोटोकॉल के लिए एक विकेन्द्रीकृत ऋण प्रोटोकॉल है। C.R.E.A.M और Yearn Finance द्वारा निर्मित, यह एक अनुमति रहित, खुला स्रोत और ब्लॉकचैन अज्ञेयवादी प्रोटोकॉल है जो एथेरियम और Fantom पर उपयोगकर्ताओं की सेवा करता है। उपयोगकर्ता पारंपरिक बचत खाते के समान, आय अर्जित करने के लिए Iron Bank में अपनी संपत्ति जमा कर सकते हैं। Iron Bank और C.R.E.A.M के बीच अंतर v1 यह है कि Iron Bank में, वःआीट-लिस्ट होने पर विश्वसनीय प्रोटोकॉल शून्य कोलैटरल ऋण ले सकते हैं।"
    },
    "ja": {
      "name": "Iron Bank",
      "description": "Iron Bankは個人、機関、プロトコルが金融サービスにアクセスするための分散型融資プロトコルです。C.R.E.A.M. FinanceがYearn Financeと共同で構築したこのプロトコルは、パーミッションレスであり、オープンソースであり、ブロックチェーンにとらわれずEthereumとFantom上にサービスを提供しています。ユーザーはIron Bankに資産を預けることで従来の普通預金と同様に利回りを得ることができます。Iron BankとC.R.E.A.M. v1の違いは、Iron Bankでは信頼できるプロトコルがホワイトリストに掲載されている場合に担保ゼロのローンを組むことができる点です。"
    },
    "id": {
      "name": "Iron Bank",
      "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted."
    },
    "ru": {
      "name": "Iron Bank",
      "description": "Iron Bank is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Built by C.R.E.A.M. Finance in collaboration with Yearn Finance, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum and Fantom. Users can deposit their assets on Iron Bank to earn yield, similar to a traditional savings account. The difference between Iron Bank and C.R.E.A.M. v1 is that in Iron Bank, trusted protocols can take out a zero collateral loan when whitelisted."
    }
  }
}
