=== yearn/ydaemon/data/meta/_config/schema/protocol.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "protocol.json",
  "title": "Protocol",
  "description": "A DeFi protocol",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "protocolVersion": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    }
  },
  "required": ["name", "description", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/protocols/1/AlphaHomora.json
{
  "$schema": "protocol",
  "name": "Alpha Homora",
  "protocolVersion": ["1"],
  "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders.",
  "localization": {
    "en": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    },
    "fr": {
      "name": "Alpha Homora",
      "description": "Alpha Homora est le premier produit de yield farming à effet de levier dans la DeFi et le premier produit d'Alpha Finance Lab. Les utilisateurs peuvent tirer parti de leurs positions et augmenter leurs rendements en empruntant des garanties provenant des prêteurs sur Alpha Homora."
    },
    "es": {
      "name": "Alpha Homora",
      "description": "Alpha Homora es el primer producto de agricultura de rendimiento apalancado en DeFi y el primer producto de Alpha Finance Lab. Los usuarios pueden apalancar sus posiciones y aumentar sus rendimientos tomando prestadas garantías proporcionadas por los prestamistas de Alpha Homora."
    },
    "de": {
      "name": "Alpha Homora",
      "description": "Alpha Homora ist das erste gehebelte Yield Farming Produkt in DeFi und das erste Produkt von Alpha Finance Lab. Die Nutzer können ihre Positionen hebeln und ihre Renditen steigern, indem sie die von den Alpha Homora Kreditgebern bereitgestellten Sicherheiten ausleihen."
    },
    "pt": {
      "name": "Alpha Homora",
      "description": "Alpha Homora é o primeiro produto de agricultura de rendimento alavancada em DeFi, e o primeiro produto de Alpha Finance Lab. Usuários podem alavancar suas posições e aumentar seus retornos ao tomar emprestado garantias disponibilizadas pelos usuários fornecedores em Alpha Homora."
    },
    "el": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    },
    "tr": {
      "name": "Alpha Homora",
      "description": "Alpha Homora, DeFi'deki ilk kaldıraçlı verim çiftçiliği ürünü ve Alpha Finance Lab'in ilk ürünüdür. Kullanıcılar, Alpha Homora kredi sağlayıcıları tarafından sağlanan teminatları ödünç alarak pozisyonlarını kaldırabilir ve getirilerini artırabilir."
    },
    "vi": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    },
    "zh": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    },
    "hi": {
      "name": "Alpha Homora",
      "description": "Alpha Homora DeFi में पहला लीवरेज्ड यील्ड फार्मिंग उत्पाद है और Alpha Finance Lab का पहला उत्पाद है। उपयोगकर्ता Alpha Homora उधारदाताओं द्वारा आपूर्ति की गई कोलेटरल उधार लेकर अपनी स्थिति का लाभ उठा सकते हैं और अपने रिटर्न को बढ़ा सकते हैं।"
    },
    "ja": {
      "name": "Alpha Homora",
      "description": "Alpha HomoraはDeFiで初めてのレバレッジイールドファームプロダクトであり、Alpha Finance Labの初めてのプロダクトです。ユーザーはAlpha Homoraの貸し手が供給する担保を借りることで自分のポジションにレバレッジをかけ、リターンを高めることができます。"
    },
    "id": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    },
    "ru": {
      "name": "Alpha Homora",
      "description": "Alpha Homora is the first leveraged yield farming product in DeFi and first product by Alpha Finance Lab. Users can lever their positions and boost their returns by borrowing collateral supplied by Alpha Homora lenders."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/1/IdleFinance.json
{
  "$schema": "protocol",
  "name": "Idle Finance",
  "protocolVersion": ["1"],
  "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy.",
  "localization": {
    "en": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    },
    "fr": {
      "name": "Idle Finance",
      "description": "Idle Finance est un protocole décentralisé de rééquilibrage. Il aide les utilisateurs à gérer automatiquement et de manière algorithmique leur allocation d'actifs numériques entre différents protocoles tiers dans la DeFi. Les utilisateurs peuvent choisir de maximiser leurs rendements des taux d'intérêt grâce à la stratégie MaxYield ou de minimiser leur exposition au risque grâce à la stratégie d'allocation RiskAdjusted."
    },
    "es": {
      "name": "Idle Finance",
      "description": "Idle Finance es un protocolo de rebalanceo descentralizado. Ayuda a los usuarios a administrar de forma automática y algorítmica su asignación de activos digitales entre diferentes protocolos DeFi de terceros. Los usuarios pueden optar por maximizar los rendimientos de las tasas de interés a través de la estrategia MaxYield o minimizar su exposición al riesgo a través de la estrategia de asignación RiskAdjusted."
    },
    "de": {
      "name": "Idle Finance",
      "description": "Idle Finance ist ein dezentrales Rebalancing-Protokoll. Es hilft den Nutzern bei der automatischen und algorithmischen Verwaltung ihrer digitalen Vermögensallokation zwischen verschiedenen DeFi-Protokollen von Drittanbietern. Die Nutzer können wählen, ob sie die Zinserträge durch die MaxYield-Strategie maximieren oder ihr Risiko durch die RiskAdjusted-Allokationsstrategie minimieren wollen."
    },
    "pt": {
      "name": "Idle Finance",
      "description": "Idle Finance é um protocolo de rebalanceamento descentralizado. Ele ajuda usuários a automaticamente e algoritmicamente gerenciar sua alocação de ativos digitais entre diferentes protocolos DeFi. Usuários podem escolher maximizar os retornos em taxas de juros através da estratégia MaxYield ou minimizar sua exposição ao risco através da alocação na estratégia RiskAdjusted."
    },
    "el": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    },
    "tr": {
      "name": "Idle Finance",
      "description": "Idle Finance, merkezi olmayan bir yeniden dengeleme protokolüdür. Kullanıcıların, farklı üçüncü taraf DeFi protokolleri arasında dijital varlık tahsislerini otomatik ve algoritmik olarak yönetmelerine yardımcı olur. Kullanıcılar, MaxYield stratejisi aracılığıyla faiz oranı getirilerini en üst düzeye çıkarmayı veya RiskAdjusted tahsis stratejisi aracılığıyla risk maruziyetlerini en aza indirmeyi seçebilir."
    },
    "vi": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    },
    "zh": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    },
    "hi": {
      "name": "Idle Finance",
      "description": "Idle Finance एक विकेन्द्रीकृत पुनर्संतुलन प्रोटोकॉल है। यह उपयोगकर्ताओं को विभिन्न तृतीय-पक्ष DeFi प्रोटोकॉल के बीच अपने डिजिटल परिसंपत्ति आवंटन को स्वचालित रूप से और एल्गोरिदमिक रूप से प्रबंधित करने में मदद करता है। उपयोगकर्ता मैक्स यील्ड रणनीति के माध्यम से ब्याज दर रिटर्न को अधिकतम करने या जोखिम समायोजित आवंटन रणनीति के माध्यम से अपने जोखिम जोखिम को कम करने का विकल्प चुन सकते हैं।"
    },
    "ja": {
      "name": "Idle Finance",
      "description": "Idle Financeは分散型リバランスプロトコルです。ユーザーが異なるサードパーティのDeFiプロトコルの間でデジタル資産の配分を自動的かつアルゴリズム的に管理するのを助けます。ユーザーはMaxYield戦略によって金利リターンを最大化するか、RiskAdjusted配分戦略によってリスクエクスポージャを最小化するかを選択することができます。"
    },
    "id": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    },
    "ru": {
      "name": "Idle Finance",
      "description": "Idle Finance is a decentralized rebalancing protocol. It helps users to automatically and algorithmically manage their digital asset allocation among different third-party DeFi protocols. Users can choose to maximize interest rate returns through MaxYield strategy or minimize their risk exposure through RiskAdjusted allocation strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/1/Synthetix.json
{
  "$schema": "protocol",
  "name": "Synthetix",
  "protocolVersion": ["1"],
  "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets.",
  "localization": {
    "en": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    },
    "fr": {
      "name": "Synthetix",
      "description": "Synthetix est l'épine dorsale du trading de produits dérivés dans la DeFi. Le protocol aide les utilisateurs à s'exposer à une vaste gamme d'actifs on-chain."
    },
    "es": {
      "name": "Synthetix",
      "description": "Synthetix es la columna vertebral para el comercio de derivados en DeFi. Ayuda a los usuarios a obtener exposición on-chain a una amplia gama de activos."
    },
    "de": {
      "name": "Synthetix",
      "description": "Synthetix ist das Kernstück des Derivatehandels in DeFi. Es hilft den Nutzern, eine breite Palette von Vermögenswerten auf der Kette kennenzulernen."
    },
    "pt": {
      "name": "Synthetix",
      "description": "Synthetix é a espinha dorsal da negociação de derivativos em DeFi. Ele ajuda os usuários a obter exposição na rede a uma vasta gama de ativos."
    },
    "el": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    },
    "tr": {
      "name": "Synthetix",
      "description": "Synthetix, DeFi'de türev ticaretinin belkemiğidir. kullanıcıların çok çeşitli varlıklara on-chain keşfetmelerini sağlar."
    },
    "vi": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    },
    "zh": {
      "name": "Synthetix",
      "description": "Synthetix 是 DeFi 衍生品交易的基石。用户通过 Synthetix 可以获得大量资产的线上交易机会。"
    },
    "hi": {
      "name": "Synthetix",
      "description": "Synthetix DeFi में डेरिवेटिव ट्रेडिंग की रीढ़ है। यह उपयोगकर्ताओं को परिसंपत्तियों की एक विस्तृत श्रृंखला के लिए ऑन-चेन एक्सपोजर हासिल करने में मदद करता है।"
    },
    "ja": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    },
    "id": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    },
    "ru": {
      "name": "Synthetix",
      "description": "Synthetix is the backbone for derivatives trading in DeFi. It helps users to gain on-chain exposure to a vast range of assets."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/250/SpiritSwap.json
{
  "$schema": "protocol",
  "name": "SpiritSwap",
  "protocolVersion": ["1"],
  "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees.",
  "localization": {
    "en": {
      "name": "SpiritSwap",
      "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees."
    },
    "fr": {
      "name": "SpiritSwap",
      "description": "SpiritSwap est un protocole market maker automatisé sur le réseau Fantom. Il s'agit d'un agrégateur de liquidités décentralisé avec lequel les utilisateurs peuvent ajouter leurs actifs dans plusieurs pools de liquidités différentes et gagner une partie des frais."
    },
    "es": {
      "name": "SpiritSwap",
      "description": "SpiritSwap es un creador automático de mercado en la red Fantom. Es un agregador de liquidez descentralizado donde los usuarios pueden agregar sus activos a varios pools de liquidez diferentes y ganar parte de las comisiones."
    },
    "de": {
      "name": "SpiritSwap",
      "description": "SpiritSwap ist ein automatisiertes Market-Maker-Protokoll im Fantom-Netzwerk. Es ist ein dezentraler Liquiditätsaggregator, bei dem Nutzer ihre Vermögenswerte zu verschiedenen Liquiditätspools hinzufügen und Gebühren verdienen können."
    },
    "pt": {
      "name": "SpiritSwap",
      "description": "SpiritSwap é um protocolo AMM na rede Fantom. É um agregador descentralizado de liquidez onde os usuários podem adicionar seus ativos em diferentes pools de liquidez e receber taxas por isto."
    },
    "el": {
      "name": "SpiritSwap",
      "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees."
    },
    "tr": {
      "name": "SpiritSwap",
      "description": "SpiritSwap, Fantom ağındaki otomatikleştirilmiş bir piyasa yapıcı protokolüdür. Kullanıcıların varlıklarını birkaç farklı likidite havuzuna ekleyebilecekleri ve ücret kazanabilecekleri merkezi olmayan bir likidite toplayıcıdır."
    },
    "vi": {
      "name": "SpiritSwap",
      "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees."
    },
    "zh": {
      "name": "SpiritSwap",
      "description": "SpiritSwap 是个在 Fantom 网络上的自动做市商协议。它是个去中心化的流动性聚合器。用户可以将他们的资产添加到各个不同的流动性池中以赚取费用。"
    },
    "hi": {
      "name": "SpiritSwap",
      "description": "SpiritSwap Fantom नेटवर्क पर एक स्वचालित बाजार निर्माता प्रोटोकॉल है। यह एक विकेन्द्रीकृत तरलता एग्रीगेटर है जहां उपयोगकर्ता अपनी संपत्ति को कई अलग-अलग तरलता पूल में जोड़ सकते हैं और शुल्क कमा सकते हैं।"
    },
    "ja": {
      "name": "SpiritSwap",
      "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees."
    },
    "id": {
      "name": "SpiritSwap",
      "description": "SpiritSwapはFantomネットワーク上の自動マーケットメーカープロトコルです。分散型流動性アグリゲーターであり、ユーザーは自分の資産をいくつかの異なる流動性プールに入金し手数料を得ることができます。"
    },
    "ru": {
      "name": "SpiritSwap",
      "description": "SpiritSwap is an automated market maker protocol on the Fantom network. It's a decentralized liquidity aggregator where users can add their assets to several different liquidity pools and earn fees."
    }
  }
}

=== yearn/ydaemon/data/meta/protocols/1/88Mph.json
{
  "$schema": "protocol",
  "name": "88 MPH",
  "protocolVersion": ["1"],
  "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token.",
  "localization": {
    "en": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "fr": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "es": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "de": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "pt": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "el": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "tr": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "vi": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "zh": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "hi": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "ja": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "id": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    },
    "ru": {
      "name": "88 MPH",
      "description": "88 MPH is a protocol which offers two non-custodial on-chain products: a fixed yield rate with a custom or preset maturity for various supplied assets, and Yield tokens, or YTs, which are tokens that allow speculators to profit from the rise in the variable yield rate of lending protocols or hedge part of their borrowing costs of a loan. For using their products users earn MPH 88 MPH's governance token."
    }
  }
}
