=== yearn/ydaemon/data/meta/_config/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "protocols": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["0xDAO", "1inch", "88 MPH", "Aave", "Abracadabra", "Alpha Homora", "Angle", "Arrakis Finance", "Aura Finance", "Balancer", "Beethoven-X", "Blockchain Adventurers Guild", "C.R.E.A.M. Finance", "Compound Finance", "Convex Finance", "Cream Finance", "Curve Finance", "Ester Finance", "Fiat DAO", "Geist Finance", "Goldfinch Finance", "Hector Finance", "Hegic", "Idle Finance", "Inverse Finance", "Iron Bank", "KeeperDAO", "League DAO", "Lido Finance", "Liquity", "MakerDAO", "Mushroom Finance", "Notional Finance", "Pool Together", "Scream", "Solidex Finance", "SpiritSwap", "SpookySwap", "Stargate Finance", "Sushi", "Synthetix", "Tarot", "Tokemak", "Uniswap", "Universe", "Vesper Finance", "Yearn", "dYdX", "veDAO", "Frax Finance", "Sturdy Finance", "Hop Exchange"]
      }
    },
    "protocolVersion": {
      "type": "object",
      "properties": {
        "0xDAO": {"type": "string", "enum": ["1"]},
        "1inch": {"type": "string", "enum": ["1"]},
        "88 MPH": {"type": "string", "enum": ["1"]},
        "Aave": {"type": "string", "enum": ["1", "2", "3"]},
        "Abracadabra": {"type": "string", "enum": ["1"]},
        "Alpha Homora": {"type": "string", "enum": ["1"]},
        "Angle": {"type": "string", "enum": ["1"]},
        "Arrakis Finance": {"type": "string", "enum": ["1"]},
        "Aura Finance": {"type": "string", "enum": ["1"]},
        "Balancer": {"type": "string", "enum": ["1", "2"]},
        "Beethoven-X": {"type": "string", "enum": ["1"]},
        "Blockchain Adventurers Guild": {"type": "string", "enum": ["1"]},
        "C.R.E.A.M. Finance": {"type": "string", "enum": ["1"]},
        "Compound Finance": {"type": "string", "enum": ["1", "2"]},
        "Convex Finance": {"type": "string", "enum": ["1"]},
        "Cream Finance": {"type": "string", "enum": ["1"]},
        "Curve Finance": {"type": "string", "enum": ["1"]},
        "Ester Finance": {"type": "string", "enum": ["1"]},
        "Fiat DAO": {"type": "string", "enum": ["1"]},
        "Geist Finance": {"type": "string", "enum": ["1"]},
        "Goldfinch Finance": {"type": "string", "enum": ["1"]},
        "Hector Finance": {"type": "string", "enum": ["1"]},
        "Hegic": {"type": "string", "enum": ["1"]},
        "Hop Exchange": {"type": "string", "enum": ["1"]},
        "Idle Finance": {"type": "string", "enum": ["1"]},
        "Inverse Finance": {"type": "string", "enum": ["1"]},
        "Iron Bank": {"type": "string", "enum": ["1"]},
        "KeeperDAO": {"type": "string", "enum": ["1"]},
        "League DAO": {"type": "string", "enum": ["1"]},
        "Lido Finance": {"type": "string", "enum": ["1"]},
        "Liquity": {"type": "string", "enum": ["1"]},
        "MakerDAO": {"type": "string", "enum": ["1"]},
        "Mushroom Finance": {"type": "string", "enum": ["1"]},
        "Notional Finance": {"type": "string", "enum": ["1"]},
        "Pool Together": {"type": "string", "enum": ["1"]},
        "Scream": {"type": "string", "enum": ["1"]},
        "Solidex Finance": {"type": "string", "enum": ["1"]},
        "SpiritSwap": {"type": "string", "enum": ["1"]},
        "SpookySwap": {"type": "string", "enum": ["1"]},
        "Stargate Finance": {"type": "string", "enum": ["1"]},
        "Sushi": {"type": "string", "enum": ["1", "Kashi"]},
        "Synthetix": {"type": "string", "enum": ["1"]},
        "Tarot": {"type": "string", "enum": ["1"]},
        "Tokemak": {"type": "string", "enum": ["1"]},
        "Uniswap": {"type": "string", "enum": ["2", "3", "2,3"]},
        "Universe": {"type": "string", "enum": ["1"]},
        "Vesper Finance": {"type": "string", "enum": ["1"]},
        "Yearn": {"type": "string", "enum": ["2"]},
        "dYdX": {"type": "string", "enum": ["1"]},
        "veDAO": {"type": "string", "enum": ["1"]},
        "Frax Finance": {"type": "string", "enum": ["1"]},
        "Sturdy Finance": {"type": "string", "enum": ["1"]}
      },
      "additionalProperties": false
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses", "protocols", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/strategies/10/AaveLenderOptimizer.json
{
  "$schema": "strategy",
  "name": "Aave Lender Optimizer",
  "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": ["0x1d3BE43C5621bdA29aB24101c54d434B9b3f29c8"],
  "protocols": ["Aave"],
  "protocolVersion": {
    "Aave": "3"
  },
  "localization": {
    "en": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "es": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "de": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "vi": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "hi": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ja": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Aave Lender Optimizer",
      "description": "Supplies {{token}} to [AAVE v3](https://app.aave.com/home) to generate interest and earn OP tokens. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/1/MushroomReinvest.json
{
  "$schema": "strategy",
  "name": "Mushroom Finance Reinvest",
  "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x53a65c8e238915c79a1e5C366Bc133162DBeE34f",
    "0x036099f243E135cf2ADF449C2dD5497Da20FB82D",
    "0xA93cb639ae732559AB9315b3A1615e624c32Cc59",
    "0xE5dc99Cbf841A6721781E592214674A87a1A70BC"
  ],
  "protocols": ["Mushroom Finance"],
  "protocolVersion": {
    "Mushroom Finance": "1"
  },
  "localization": {
    "en": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Mushroom Finance Reinvest",
      "description": "Fournit du {{token}} sur le [Mushroom Finance](https://mushrooms.finance) {{token}} Vault pour gagner du MM. Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "Mushroom Finance Reinvest",
      "description": "Suministra {{token}} a la vault de {{token}} en [Mushroom Finance](https://mushrooms.finance) para ganar MM. Los tokens ganados se cosechan, se venden por más {{token}} que se depositan nuevamente en la estrategia."
    },
    "de": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Mushroom Finance Reinvest",
      "description": "MM kazanmak için [Mushroom Finance](https://mushrooms.finance) {{token}} Vault'una {{token}} sağlar. Kazanılan jetonlar toplanır, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Mushroom Finance Reinvest",
      "description": "将 {{token}} 存入 [Mushroom Finance](https://mushrooms.finance) 的 {{token}} 机枪池赚取 MM。收获代币后，卖掉换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "Mushroom Finance Reinvest",
      "description": "MM कमाने के लिए {{token}} को [Mushroom Finance](https://mushrooms.finance) {{token}} को सप्लाई करता है। अर्जित टोकन वसूल किया जाता है, अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Mushroom Finance Reinvest",
      "description": "Supplies {{token}} to [Mushroom Finance](https://mushrooms.finance) {{token}} Vault to earn MM. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/250/0xDAOReinvest.json
{
  "$schema": "strategy",
  "name": "0xDAO Reinvest",
  "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x585D4024C6aB31b67Dfd1624F2cA01Eb1dBe8D22",
    "0x76e32c811Cad5b835B780461efd202D561723D14",
    "0x177E745771494F1FF8Ed3FCDcdfF02213A1AD761",
    "0x44E0403e7Ee547F522BbBA5f49fd04a432d2ad82",
    "0xcF37B4a55f06dDA65591B1AF56812c5bb7E6d336",
    "0x71304d618bd2F1334d25F3aC836a2BA94A0622Ae",
    "0xA36c91E38bf24E9F2df358E47D4134a8894C6a4c"
  ],
  "protocols": ["0xDAO"],
  "protocolVersion": {
    "0xDAO": "1"
  },
  "localization": {
    "en": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "0xDAO Reinvest",
      "description": "Fournit du {{token}} sur [0xDAO](https://www.oxdao.fi) pour gagner des OXD. Les jetons gagnés sont récoltés, vendus pour plus de {{token}}, qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "0xDAO Reinvest",
      "description": "Suministra {{token}} a [0xDAO](https://www.oxdao.fi) para ganar OXD. Los tokens ganados se cosechan, se venden por más {{token}} que se deposita nuevamente en la estrategia."
    },
    "de": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "0xDAO Reinvest",
      "description": "OXD kazanmak için [0xDAO](https://www.oxdao.fi)'ya {{token}} sağlar. Kazanılan jetonlar toplanır, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "0xDAO Reinvest",
      "description": "将 {{token}} 存入 [0xDAO](https://www.oxdao.fi) 以赚取 OXD。收获的 OXD 将被卖掉换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "0xDAO Reinvest",
      "description": "OXD कमाने के लिए {{token}} से [0xDAO](https://www.oxdao.fi) की आपूर्ति करता है। अर्जित टोकन वसूल किया जाता है, अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "0xDAO Reinvest",
      "description": "Supplies {{token}} to [0xDAO](https://www.oxdao.fi) to earn OXD. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/1/LiquityStabilityPool.json
{
  "$schema": "strategy",
  "name": "LiquityUSD Stability Pool Strategy",
  "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x8ec4c06960c6BDBb4964D1830aC1355EE78401bD",
    "0xA9B6226C1Ea64a6515e5Ae572AC1D806cD956E26",
    "0xFf72f7C5f64ec2fd79B57d1A69C3311C1bB3EEF1"
  ],
  "protocols": ["Liquity"],
  "protocolVersion": {
    "Liquity": "1"
  },
  "localization": {
    "en": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Fournit du {{token}} sur la pool de stabilité de Liquity pour gagner des récompenses LQTY et des ETH (à partir de liquidations). Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Suministra {{token}} al grupo de estabilidad de Liquity para ganar recompensas LQTY y ETH (de liquidaciones de tesoros). Los tokens ganados se cosechan y venden por más {{token}} que se deposita nuevamente en la estrategia."
    },
    "de": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "LQTY ödülleri ve ETH(hazinedeki tasfiyelerinden) kazanmak için Liquity'nin Stability Havuzuna {{token}} sağlar. Kazanılan jetonlar toplanır ve stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "将 {{token}} 存入 Liquity 的稳定池赚取 LQTY 奖励和 ETH（来自清算）。收获代币后，卖掉换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "LQTY पुरस्कार और ETH (ट्रोव परिसमापन से) अर्जित करने के लिए Liquity के स्थिरता पूल को {{token}} की आपूर्ति करता है। अर्जित टोकन वसूल किया जाता है और अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "LiquityUSD Stability Pool Strategy",
      "description": "Supplies {{token}} to Liquity's Stability Pool to earn LQTY rewards and ETH (from trove liquidations). Earned tokens are harvested and sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/1/PoolTogetherReinvest.json
{
  "$schema": "strategy",
  "name": "Pool Together Reinvest",
  "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy.",
  "addresses": [
    "0x387fCa8d7e2e09655b4F49548607B55C0580fC63",
    "0x6EB00860260CF51623737e17579Db797d71cd337",
    "0x57e848A6915455a7e77CF0D55A1474bEFd9C374d"
  ],
  "protocols": ["Pool Together"],
  "protocolVersion": {
    "Pool Together": "1"
  },
  "localization": {
    "en": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "fr": {
      "name": "Pool Together Reinvest",
      "description": "Fournit du {{token}} sur [Pool Together](https://app.pooltogether.com) pour gagner du POOL. Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie. Si stratégie remporte le prix de la semaine, le prix sera également ajouté à la stratégie."
    },
    "es": {
      "name": "Pool Together Reinvest",
      "description": "Suministra {{token}} a [Pool Together](https://app.pooltogether.com) para ganar POOL. Los tokens ganados se cosechan, se venden por más {{token}} que se deposita nuevamente en la estrategia. Si la estrategia gana el premio de la semana, el premio también se agregará a la estrategia.."
    },
    "de": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "pt": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "el": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "tr": {
      "name": "Pool Together Reinvest",
      "description": "POOL kazanmak için [Pool Together](https://app.pooltogether.com)'a {{token}} sağlar. Kazanılan jetonlar toplanır, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır. Strateji haftanın ödülünü kazanırsa, ödül de stratejiye eklenecektir."
    },
    "vi": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "zh": {
      "name": "Pool Together Reinvest",
      "description": "将 {{token}} 存入 [Pool Together](https://app.pooltogether.com) 赚取 POOL 奖励。收获奖励后卖掉换为更多的 {{token}} 并进行复投。如果本周中奖，奖金也会被复投。"
    },
    "hi": {
      "name": "Pool Together Reinvest",
      "description": "POOL कमाने के लिए {{token}} को [Pool Together](https://app.pooltogether.com) पर सप्लाई करता है। अर्जित टोकन वसूल किया जाता है, अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है। यदि रणनीति सप्ताह का पुरस्कार जीतती है, तो पुरस्कार भी रणनीति में जोड़ा जाएगा।"
    },
    "ja": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "id": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    },
    "ru": {
      "name": "Pool Together Reinvest",
      "description": "Supplies {{token}} to [Pool Together](https://app.pooltogether.com) to earn POOL. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy. If strategy wins prize of the week, prize will also be added to the strategy."
    }
  }
}
