=== yearn/ydaemon/data/meta/_config/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "protocols": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["0xDAO", "1inch", "88 MPH", "Aave", "Abracadabra", "Alpha Homora", "Angle", "Arrakis Finance", "Aura Finance", "Balancer", "Beethoven-X", "Blockchain Adventurers Guild", "C.R.E.A.M. Finance", "Compound Finance", "Convex Finance", "Cream Finance", "Curve Finance", "Ester Finance", "Fiat DAO", "Geist Finance", "Goldfinch Finance", "Hector Finance", "Hegic", "Idle Finance", "Inverse Finance", "Iron Bank", "KeeperDAO", "League DAO", "Lido Finance", "Liquity", "MakerDAO", "Mushroom Finance", "Notional Finance", "Pool Together", "Scream", "Solidex Finance", "SpiritSwap", "SpookySwap", "Stargate Finance", "Sushi", "Synthetix", "Tarot", "Tokemak", "Uniswap", "Universe", "Vesper Finance", "Yearn", "dYdX", "veDAO", "Frax Finance", "Sturdy Finance", "Hop Exchange"]
      }
    },
    "protocolVersion": {
      "type": "object",
      "properties": {
        "0xDAO": {"type": "string", "enum": ["1"]},
        "1inch": {"type": "string", "enum": ["1"]},
        "88 MPH": {"type": "string", "enum": ["1"]},
        "Aave": {"type": "string", "enum": ["1", "2", "3"]},
        "Abracadabra": {"type": "string", "enum": ["1"]},
        "Alpha Homora": {"type": "string", "enum": ["1"]},
        "Angle": {"type": "string", "enum": ["1"]},
        "Arrakis Finance": {"type": "string", "enum": ["1"]},
        "Aura Finance": {"type": "string", "enum": ["1"]},
        "Balancer": {"type": "string", "enum": ["1", "2"]},
        "Beethoven-X": {"type": "string", "enum": ["1"]},
        "Blockchain Adventurers Guild": {"type": "string", "enum": ["1"]},
        "C.R.E.A.M. Finance": {"type": "string", "enum": ["1"]},
        "Compound Finance": {"type": "string", "enum": ["1", "2"]},
        "Convex Finance": {"type": "string", "enum": ["1"]},
        "Cream Finance": {"type": "string", "enum": ["1"]},
        "Curve Finance": {"type": "string", "enum": ["1"]},
        "Ester Finance": {"type": "string", "enum": ["1"]},
        "Fiat DAO": {"type": "string", "enum": ["1"]},
        "Geist Finance": {"type": "string", "enum": ["1"]},
        "Goldfinch Finance": {"type": "string", "enum": ["1"]},
        "Hector Finance": {"type": "string", "enum": ["1"]},
        "Hegic": {"type": "string", "enum": ["1"]},
        "Hop Exchange": {"type": "string", "enum": ["1"]},
        "Idle Finance": {"type": "string", "enum": ["1"]},
        "Inverse Finance": {"type": "string", "enum": ["1"]},
        "Iron Bank": {"type": "string", "enum": ["1"]},
        "KeeperDAO": {"type": "string", "enum": ["1"]},
        "League DAO": {"type": "string", "enum": ["1"]},
        "Lido Finance": {"type": "string", "enum": ["1"]},
        "Liquity": {"type": "string", "enum": ["1"]},
        "MakerDAO": {"type": "string", "enum": ["1"]},
        "Mushroom Finance": {"type": "string", "enum": ["1"]},
        "Notional Finance": {"type": "string", "enum": ["1"]},
        "Pool Together": {"type": "string", "enum": ["1"]},
        "Scream": {"type": "string", "enum": ["1"]},
        "Solidex Finance": {"type": "string", "enum": ["1"]},
        "SpiritSwap": {"type": "string", "enum": ["1"]},
        "SpookySwap": {"type": "string", "enum": ["1"]},
        "Stargate Finance": {"type": "string", "enum": ["1"]},
        "Sushi": {"type": "string", "enum": ["1", "Kashi"]},
        "Synthetix": {"type": "string", "enum": ["1"]},
        "Tarot": {"type": "string", "enum": ["1"]},
        "Tokemak": {"type": "string", "enum": ["1"]},
        "Uniswap": {"type": "string", "enum": ["2", "3", "2,3"]},
        "Universe": {"type": "string", "enum": ["1"]},
        "Vesper Finance": {"type": "string", "enum": ["1"]},
        "Yearn": {"type": "string", "enum": ["2"]},
        "dYdX": {"type": "string", "enum": ["1"]},
        "veDAO": {"type": "string", "enum": ["1"]},
        "Frax Finance": {"type": "string", "enum": ["1"]},
        "Sturdy Finance": {"type": "string", "enum": ["1"]}
      },
      "additionalProperties": false
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses", "protocols", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/strategies/1/LiquityFeeClaimReinvest.json
{
  "$schema": "strategy",
  "name": "Liquity Fee Claim and Reinvest",
  "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY.",
  "addresses": ["0x478085739EA884F38Add4D36872aCd8333b5D4D6"],
  "protocols": ["Liquity"],
  "protocolVersion": {
    "Liquity": "1"
  },
  "localization": {
    "en": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "fr": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "es": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "de": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "pt": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "el": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "tr": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "vi": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "zh": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "hi": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "ja": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "id": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    },
    "ru": {
      "name": "Liquity Fee Claim and Reinvest",
      "description": "Accepts {{token}} and stakes it at [Liquity](https://liquity.app/) to earn LUSD and ETH. Earned rewards are harvested, swapped for more {{token}} which is deposited back into the strategy. Native rewards are increased via yLQTY Booster, which donates yield from staking Yearn's protocol-owned LQTY."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/250/SpookyJointProviderHedged.json
{
  "$schema": "strategy",
  "name": "Spooky Joint Provider Hedged",
  "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x9b536FD704944110d5F742840a206C45f6858920",
    "0x84A92b621897Bf7e4a95e80d91b3ab7491e9Db39",
    "0x32d1BC9133f46E4442b9666Bbc361bB90CE49a1A",
    "0x60fa432fc8494FE0b7A7654295e178F6F2f22405",
    "0x15faeCDDAD6f3073954b29761b94b0b28321586f",
    "0x4183e99e7C3874F85d195698AFb7ee1289DA0AFe",
    "0x4bd6976358e419Ce96103c70B776C273A9f4a8AD",
    "0x61D5ed97b899347c1F286a9a67622d337D0e61fE",
    "0x098B187d4df62de7ff9f3366b1B280F06cE86A73",
    "0x939dC1C32D89Ba771c1Eeee8f1a12bA9b766C532",
    "0xD58003b2Bac011b67C108b24e5deb1B22c70Fd1f",
    "0x99781f4324CF60D96195276822D2518fC85C11Fa",
    "0x84f9E6d5D28Edf0AE873A4d84903716684f473D5",
    "0xc7a336925674EFeef22cEB56364e3658B8a0D467",
    "0x8Ee822d31c6F92063AA7EA723B94AC94D0cC9D64",
    "0xA4F10BC80F6c5cf6A34F828cb53c243eB1976Da8",
    "0x7114cAD096731F4d0B8E0De6e7CeDc189A462dce",
    "0xFA01ca21239166701B6760d162257b449ba6D011"
  ],
  "protocols": ["SpookySwap"],
  "protocolVersion": {
    "SpookySwap": "1"
  },
  "localization": {
    "en": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Fournit du {{token}} sur le coté d'une pool [SpookySwap](https://spookyswap.finance/farms). Cette stratégie limite également les pertes impermanentes via Hedgil dans une plage protégée tout en gagnant des jetons BOO et des frais. Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Suministra {{token}} como la mitad de un proveedor de liquidez conjunto para un grupo en [SpookySwap](https://spookyswap.finance/farms) y también esta estrategia limita la pérdida impermanente a través de Hedgil en un rango protegido mientras gana BOO y tarifas. Los tokens ganados se cosechan, se dividen entre los tokens, se venden por más {{token}} que se deposita nuevamente en la estrategia."
    },
    "de": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Spooky Joint Provider Hedged",
      "description": "[SpookySwap](https://spookyswap.finance/farms) üzerindeki bir havuz için ortak bir likidite sağlayıcısının yarısı olarak {{token}} sağlar ayrıca bu strateji, BOO ve ücretler kazanırken Hedgil aracılığıyla Korumalı bir aralıkta Geçici Zararı sınırlar. Kazanılan jetonlar hasat edilir, jetonlar arasında bölünür, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Spooky Joint Provider Hedged",
      "description": "将 {{token}} 作为流动性的一半放入 [SpookySwap](https://spookyswap.finance/farms) 赚取 BOO 和交易手续费。此策略也同时应用 Hedgil 做对冲以将无偿损失控制在可控范围。收获到的奖励会分配给交易对的两个代币，卖掉，换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "Spooky Joint Provider Hedged",
      "description": "[SpookySwap](https://spookyswap.finance/farms) पर एक पूल के लिए एक संयुक्त तरलता प्रदाता के आधे के रूप में आपूर्ति {{token}}, यह रणनीति BOO और शुल्क अर्जित करते हुए एक संरक्षित सीमा में Hedgil के माध्यम से अस्थायी नुकसान को सीमित करती है। अर्जित टोकन वसूल किया जाता है, टोकन के बीच विभाजित किया जाता है, और अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Spooky Joint Provider Hedged",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a pool on [SpookySwap](https://spookyswap.finance/farms) also this strategy limits Impermanent Loss via Hedgil in a protected range while earning BOO and fees. Earned tokens are harvested, divided between the tokens, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/250/GeistBorrow.json
{
  "$schema": "strategy",
  "name": "Geist Borrow",
  "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x2195810c2A937259053C25AFc8D221ae2369cBAC",
    "0xa09cC3C8b05eDC7eA9615fA8bb8e904814C73a15",
    "0xcCd1938Ea67BFf58f859512F7C8E5b70928020E2",
    "0x0e207674E05dC6Ff7fE949eB57409bF3B980FF41"
  ],
  "protocols": ["Geist Finance"],
  "protocolVersion": {
    "Geist Finance": "1"
  },
  "localization": {
    "en": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Geist Borrow",
      "description": "Fournit du {{token}} sur [Geist Finance](https://geist.finance/deposit) pour générer des intérêts et gagner des GEIST. Cette stratégie emprunte également des jetons contre le {{token}}. Les jetons empruntés sont ensuite déposés dans le yVault correspondant pour générer du rendement. Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "Geist Borrow",
      "description": "Suministra {{token}} a [Geist Finance](https://geist.finance/deposit) para generar intereses y ganar GEIST. Esta estrategia también toma prestados tokens contra {{token}}. Los tokens prestados luego se depositan en el yVault correspondiente para generar rendimiento. Los tokens ganados se cosechan, se venden por más {{token}} que se deposita nuevamente en la estrategia."
    },
    "de": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Geist Borrow",
      "description": "Faiz ve GEIST kazanmak için [Geist Finance](https://geist.finance/deposit)'e {{token}} sağlar. Bu strateji ayrıca {{token}} karşılığında token ödünç alır. Ödünç alınan token'ler daha sonra verim elde etmek için ilgili yVault'a yatırılır. Kazanılan jetonlar toplanır, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Geist Borrow",
      "description": "将 {{token}} 存入 [Geist Finance](https://geist.finance/deposit) 以赚取利息和 GEIST 奖励。此策略也用 {{token}} 作为抵押品借出其他代币。借到的代币会被存入对应的 yVault 以产生收益。收获赚取到的代币会卖掉，换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "Geist Borrow",
      "description": "ब्याज उत्पन्न करने और GEIST अर्जित करने के लिए {{token}} [Geist Finance](https://geist.finance/deposit) को आपूर्ति करता है। यह रणनीति {{token}} के बदले टोकन भी लेती है। उधार लिए गए टोकन को उपज उत्पन्न करने के लिए संबंधित yVault में जमा किया जाता है। अर्जित टोकन काटा जाता है, अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Geist Borrow",
      "description": "Supplies {{token}} to [Geist Finance](https://geist.finance/deposit) to generate interest and earn GEIST. This strategy also borrows tokens against {{token}}. Borrowed tokens are then deposited into the corresponding yVault to generate yield. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}
