=== yearn/ydaemon/data/meta/_config/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "protocols": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["0xDAO", "1inch", "88 MPH", "Aave", "Abracadabra", "Alpha Homora", "Angle", "Arrakis Finance", "Aura Finance", "Balancer", "Beethoven-X", "Blockchain Adventurers Guild", "C.R.E.A.M. Finance", "Compound Finance", "Convex Finance", "Cream Finance", "Curve Finance", "Ester Finance", "Fiat DAO", "Geist Finance", "Goldfinch Finance", "Hector Finance", "Hegic", "Idle Finance", "Inverse Finance", "Iron Bank", "KeeperDAO", "League DAO", "Lido Finance", "Liquity", "MakerDAO", "Mushroom Finance", "Notional Finance", "Pool Together", "Scream", "Solidex Finance", "SpiritSwap", "SpookySwap", "Stargate Finance", "Sushi", "Synthetix", "Tarot", "Tokemak", "Uniswap", "Universe", "Vesper Finance", "Yearn", "dYdX", "veDAO", "Frax Finance", "Sturdy Finance", "Hop Exchange"]
      }
    },
    "protocolVersion": {
      "type": "object",
      "properties": {
        "0xDAO": {"type": "string", "enum": ["1"]},
        "1inch": {"type": "string", "enum": ["1"]},
        "88 MPH": {"type": "string", "enum": ["1"]},
        "Aave": {"type": "string", "enum": ["1", "2", "3"]},
        "Abracadabra": {"type": "string", "enum": ["1"]},
        "Alpha Homora": {"type": "string", "enum": ["1"]},
        "Angle": {"type": "string", "enum": ["1"]},
        "Arrakis Finance": {"type": "string", "enum": ["1"]},
        "Aura Finance": {"type": "string", "enum": ["1"]},
        "Balancer": {"type": "string", "enum": ["1", "2"]},
        "Beethoven-X": {"type": "string", "enum": ["1"]},
        "Blockchain Adventurers Guild": {"type": "string", "enum": ["1"]},
        "C.R.E.A.M. Finance": {"type": "string", "enum": ["1"]},
        "Compound Finance": {"type": "string", "enum": ["1", "2"]},
        "Convex Finance": {"type": "string", "enum": ["1"]},
        "Cream Finance": {"type": "string", "enum": ["1"]},
        "Curve Finance": {"type": "string", "enum": ["1"]},
        "Ester Finance": {"type": "string", "enum": ["1"]},
        "Fiat DAO": {"type": "string", "enum": ["1"]},
        "Geist Finance": {"type": "string", "enum": ["1"]},
        "Goldfinch Finance": {"type": "string", "enum": ["1"]},
        "Hector Finance": {"type": "string", "enum": ["1"]},
        "Hegic": {"type": "string", "enum": ["1"]},
        "Hop Exchange": {"type": "string", "enum": ["1"]},
        "Idle Finance": {"type": "string", "enum": ["1"]},
        "Inverse Finance": {"type": "string", "enum": ["1"]},
        "Iron Bank": {"type": "string", "enum": ["1"]},
        "KeeperDAO": {"type": "string", "enum": ["1"]},
        "League DAO": {"type": "string", "enum": ["1"]},
        "Lido Finance": {"type": "string", "enum": ["1"]},
        "Liquity": {"type": "string", "enum": ["1"]},
        "MakerDAO": {"type": "string", "enum": ["1"]},
        "Mushroom Finance": {"type": "string", "enum": ["1"]},
        "Notional Finance": {"type": "string", "enum": ["1"]},
        "Pool Together": {"type": "string", "enum": ["1"]},
        "Scream": {"type": "string", "enum": ["1"]},
        "Solidex Finance": {"type": "string", "enum": ["1"]},
        "SpiritSwap": {"type": "string", "enum": ["1"]},
        "SpookySwap": {"type": "string", "enum": ["1"]},
        "Stargate Finance": {"type": "string", "enum": ["1"]},
        "Sushi": {"type": "string", "enum": ["1", "Kashi"]},
        "Synthetix": {"type": "string", "enum": ["1"]},
        "Tarot": {"type": "string", "enum": ["1"]},
        "Tokemak": {"type": "string", "enum": ["1"]},
        "Uniswap": {"type": "string", "enum": ["2", "3", "2,3"]},
        "Universe": {"type": "string", "enum": ["1"]},
        "Vesper Finance": {"type": "string", "enum": ["1"]},
        "Yearn": {"type": "string", "enum": ["2"]},
        "dYdX": {"type": "string", "enum": ["1"]},
        "veDAO": {"type": "string", "enum": ["1"]},
        "Frax Finance": {"type": "string", "enum": ["1"]},
        "Sturdy Finance": {"type": "string", "enum": ["1"]}
      },
      "additionalProperties": false
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses", "protocols", "protocolVersion"]
}

=== yearn/ydaemon/data/meta/strategies/10/HopReinvest.json
{
  "$schema": "strategy",
  "name": "Hop Single Sided",
  "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy.",
  "addresses": [
    "0x3c023B5Fa6D003d72b32C92057c153b1a8e4Fe38",
    "0x94E747E1AA9a9c3b1B8ED388E207fe5424870d0d",
    "0x99519771c569bC11cd652A5415672f54476cDbFe",
    "0xC93CcF5fA33Bb2952bB28e0636974030ba039385",
    "0x5F1620f50a79aF8B9829f87376AfCeBdc3DEB355",
    "0xe224d81E7159a1803B5Ad725DF2eB03aD20a103d",
    "0x275a0cA8f321035a20C163B8dE079BaBd0c0992B",
    "0x564dFB09f7fcBDBc25443F137218286BF1059b75"
  ],
  "protocols": ["Hop Exchange"],
  "protocolVersion": {
    "Hop Exchange": "1"
  },
  "localization": {
    "en": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "fr": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "es": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "de": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "pt": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "el": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "tr": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "vi": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "zh": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "hi": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "ja": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "id": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    },
    "ru": {
      "name": "Hop Single Sided",
      "description": "Supplies {{token}} to a liquidity pool on [Hop Exchange](https://app.hop.exchange/#/pools) and stakes it to earn HOP and trading fees. Rewards are harvested, sold for more {{token}}, and deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/1/IdleReinvest.json
{
  "$schema": "strategy",
  "name": "Idle Finance Reinvest",
  "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0x9f51F4df0b275dfB1F74f6Db86219bAe622B36ca",
    "0x2E1ad896D3082C52A5AE7Af307131DE7a37a46a0",
    "0x01b54c320d6B3057377cbc71d953d1BBa84df44e",
    "0x5D411D2cde10e138d68517c42bE2808C90c22026",
    "0x3E14d864E4e82eD98849Bf666971f39Cf49Ca986",
    "0x030bFfF524BbE7A77C789A0993cE8EF23cF8Efe9",
    "0xcbBC393970DF99d2a63e845353Dbdb040d3EEe7C",
    "0x9b8F90078E74AcaD449798554f1bE3F4157C932D",
    "0x157fE71B86AE9200A93054c8d91b5B5d8a7a67F9",
    "0x414D8F5c21dAF33105eE6416bcdA99a50A47C0e5",
    "0x79B3D0A9513C49D7Ea4BD6868a08aD966eC18f46",
    "0x71041489ddAb466de443eC4Ea39D60b54193BcA1",
    "0x39a382ece7534601B218BdD8AdCEA215CBE2440b",
    "0xA04fE40eD8a8a8d657E41276ec9e9Ee877675e34",
    "0xaC05d96ba2A6252121E2a38c1F37657148d8CF80",
    "0x7f2CcF4e38599C4b4a1FB4aC33B32a4796aCcC03",
    "0x644501563ebE624eaAC6532681aD09fCFd9Ca65f",
    "0xD551f51A03Fc1902700F4263D4a1F8327E3cc604",
    "0x9A00F6b8D484d670604338d793a6E36249e4322F",
    "0x6312a91f7390CAD51772676474a43f9AE94dd60e",
    "0x016919386387898E4Fa87c7c4D3324F75f178F12",
    "0x1de1401c71362C05C680c5Fd073888719d8f4196",
    "0x66f7b6E7EB858075d6F2c5615F22659a1A20f6D6"
  ],
  "protocols": ["Idle Finance"],
  "protocolVersion": {
    "Idle Finance": "1"
  },
  "localization": {
    "en": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Idle Finance Reinvest",
      "description": "Fournit du {{token}} sur [Idle Finance](https://idle.finance) pour gagner des IDLE et COMP. Les jetons gagnés sont récoltés, vendus pour plus de {{token}} qui sont ensuite redéposés dans la stratégie."
    },
    "es": {
      "name": "Idle Finance Reinvest",
      "description": "Suministra {{token}} a [Idle Finance](https://idle.finance) para ganar IDLE y COMP. Los tokens ganados se cosechan y se venden por más {{token}} que se deposita nuevamente en la estrategia."
    },
    "de": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Idle Finance Reinvest",
      "description": "IDLE ve COMP kazanmak için [Idle Finance](https://idle.finance)'a {{token}} sağlar. Kazanılan jetonlar toplanır, stratejiye geri yatırılan daha fazla {{token}} karşılığında satılır."
    },
    "vi": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Idle Finance Reinvest",
      "description": "将 {{token}} 存入 [Idle Finance](https://idle.finance) 赚取 IDLE 和 COMP。收获代币奖励后，卖掉换为更多的 {{token}} 并进行复投。"
    },
    "hi": {
      "name": "Idle Finance Reinvest",
      "description": "IDLE और COMP कमाने के लिए {{token}} को [Idle Finance](https://idle.finance) को सप्लाई करता है। अर्जित टोकन वसूल किया जाता है, अधिक {{token}} के लिए बेचा जाता है जिसे वापस रणनीति में जमा किया जाता है।"
    },
    "ja": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Idle Finance Reinvest",
      "description": "Supplies {{token}} to [Idle Finance](https://idle.finance) to earn IDLE and COMP. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/1/AngleReinvest.json
{
  "$schema": "strategy",
  "name": "Angle Reinvest",
  "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy.",
  "addresses": [
    "0xcFa730D6CD6568872C18101442228499229fb70E",
    "0x98fBB6Fd927bE3a98563E66E1ef8Ae0C2016505F",
    "0x2CB390212b0e5091a3c0D0331669c1419165CF80",
    "0x7C2b9DB2Ae5aCC6fAC2Fd6cE9b01A5EB4bDD1309"
  ],
  "protocols": ["Angle"],
  "protocolVersion": {
    "Angle": "1"
  },
  "localization": {
    "en": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "fr": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "es": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "de": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "pt": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "el": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "tr": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "vi": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "zh": {
      "name": "Angle Reinvest",
      "description": "存入 {{token}} 到 [Angle Protocol](https://app.angle.money/#/slp) 做 sanToken 的流动性提供者，然后做质押以赚取 ANGLE。赚取到的代币被收获后，卖掉换为更多的 {{token}} 再进行复投。"
    },
    "hi": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ja": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "id": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    },
    "ru": {
      "name": "Angle Reinvest",
      "description": "Supplies {{token}} to [Angle Protocol](https://app.angle.money/#/slp) as a Standard Liquidity Provider for sanTokens which are staked to earn ANGLE. Earned tokens are harvested, sold for more {{token}} which is deposited back into the strategy."
    }
  }
}

=== yearn/ydaemon/data/meta/strategies/250/0xDAOJointProviderArb.json
{
  "$schema": "strategy",
  "name": "0xDAO Joint Provider Arbitrager",
  "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit.",
  "addresses": ["0xb99d6662127d9A3c68Bc949679f364E1739E2CA1"],
  "protocols": ["0xDAO"],
  "protocolVersion": {
    "0xDAO": "1"
  },
  "localization": {
    "en": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "fr": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "es": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "de": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "pt": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "el": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "tr": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "vi": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "zh": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "hi": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "[0xDAO](https://oxdao.fi) Volatile Pool के लिए संयुक्त तरलता प्रदाता के आधे के रूप में {{token}} की आपूर्ति करता है जिसमें SOLID और OXD कमाने के लिए पेग्ड टोकन होते हैं। अर्जित टोकन को वसूल कियाा जाता है, जोड़ी के बीच विभाजित किया जाता है जिसे वापस रणनीति में जमा किया जाता है। जमा करने से पहले चेक करता है अगर पूल ऑफ-पेग है। यदि ऐसा है, तो यह शेष राशि और लाभ संतुलन को ठीक करने के लिए जमा करता है।"
    },
    "ja": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "id": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    },
    "ru": {
      "name": "0xDAO Joint Provider Arbitrager",
      "description": "Supplies {{token}} as half of a joint liquidity provider for a [0xDAO](https://oxdao.fi) Volatile Pool which consists of pegged tokens to earn SOLID and OXD. Earned tokens are harvested, divided between the pair which is deposited back into the strategy. Checks before depositing, if the pool is off-peg. If so, it deposits to fix the balance and profit."
    }
  }
}
