=== yearn/ydaemon/data/meta/_config/schema/token.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "token.json",
  "title": "Token",
  "description": "An underlying token of a Yearn vault",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "symbol": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "fr": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "es": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "de": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "pt": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "el": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "tr": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "vi": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "zh": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "hi": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "ja": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "id": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        },
        "ru": {
          "type": "object",
          "required": ["description"],
          "properties": { "description": { "type": "string" } }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "website": {
      "type": "string"
    }
  },
  "required": []
}

=== yearn/ydaemon/data/meta/tokens/1/0x453D92C7d4263201C69aACfaf589Ed14202d83a4.json
{
  "$schema": "token",
  "name": "Curve yCRV Pool",
  "symbol": "yCRV-f",
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'",
  "categories": ["Curve LP Tokens"],
  "website": "https://curve.fi/",
  "localization": {
    "en": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "fr": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "es": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "de": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "pt": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "el": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "tr": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "vi": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "zh": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "hi": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "ja": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "id": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    },
    "ru": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains yCRV and CRV. CRV is Curve's governance token, and yCRV is Yearn's new liquid veCRV wrapper, redesigned from the ground up to give users 'the best CRV yields in DeFi'"
    }
  }
}

=== yearn/ydaemon/data/meta/tokens/1/0x9fC689CCaDa600B6DF723D9E47D84d76664a1F23.json
{
  "$schema": "token",
  "name": "Curve USDT Pool",
  "symbol": "crvUSDT",
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum.",
  "categories": ["Curve LP Tokens"],
  "website": "https://www.curve.fi/",
  "localization": {
    "en": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "fr": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "es": {
      "description": "Este token representa un grupo de liquidez de Curve. Los titulares obtienen tarifas de los usuarios que comercian en el grupo y también pueden depositar el LP en los gauges de Curve para obtener emisiones de CRV. Este grupo contiene DAI, USDC y USDT que se prestan a Compound, un mercado monetario descentralizado en Ethereum."
    },
    "de": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "pt": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "el": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "tr": {
      "description": "Bu jeton, bir Curve likidite havuzunu temsil eder. Sahipler, havuzda işlem yapan kullanıcılardan ücret alır ve ayrıca CRV emisyonları kazanmak için LP'yi Curve'un göstergelerine yatırabilir. Bu havuz, Ethereum'da merkezi olmayan bir para piyasası olan Compound'a ödünç verilen DAI, USDC ve USDT'yi içerir."
    },
    "vi": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "zh": {
      "description": "此代币是 Curve 的流动性池代币。代币持有者可以赚取交易费，也可以将代币存入 Curve gauge 以获得 CRV 奖励。其中包含借给 Compound 的 DAI, USDC, 和 USDT，Compound 是以太坊上的去中心化货币市场。"
    },
    "hi": {
      "description": "यह टोकन Curve लिक्विडिटी पूल का प्रतिनिधित्व करता है। धारक पूल में व्यापार करने वाले उपयोगकर्ताओं से शुल्क कमाते हैं, और CRV उत्सर्जन अर्जित करने के लिए LP को Curve के गेज में जमा कर सकते हैं। इस पूल में DAI, USDC और USDT शामिल हैं जो Compound को उधार दिए गए हैं, जो एथेरियम पर एक विकेन्द्रीकृत मुद्रा बाजार है।"
    },
    "ja": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "id": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    },
    "ru": {
      "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Compound, a decentralized money market on Ethereum."
    }
  }
}
