=== yearn/ydaemon/data/meta/_config/schema/vault.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "vault.json",
	"title": "Vault",
	"description": "A Yearn vault",
	"type": "object",
	"properties": {
		"comment": {
			"type": "string"
		},
		"hideAlways": {
			"type": "boolean"
		},
		"useVaultDataAsDefault": {
			"type": "boolean"
		},
		"depositsDisabled": {
			"type": "boolean"
		},
		"withdrawalsDisabled": {
			"type": "boolean"
		},
		"apyOverride": {
			"type": "number"
		},
		"apyTypeOverride": {
			"type": "string"
		},
		"order": {
			"type": "number"
		},
		"migrationAvailable": {
			"type": "boolean"
		},
		"allowZapIn": {
			"type": "boolean"
		},
		"allowZapOut": {
			"type": "boolean"
		},
		"zapInWith": {
			"type": "string"
		},
		"zapOutWith": {
			"type": "string"
		},
		"migrationContract": {
			"type": "string",
			"format": "address"
		},
		"migrationTargetVault": {
			"type": "string",
			"format": "address"
		},
		"retired": {
			"type": "boolean"
		},
		"displayName": {
			"type": "string"
		},
		"vaultIconOverride": {
			"type": "string"
		},
		"vaultSymbolOverride": {
			"type": "string"
		},
		"vaultNameOverride": {
			"type": "string"
		},
		"vaultDetailPageAssets": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"classification": {
			"type": "object",
			"properties": {
				"isPool": {"type": "boolean"},
				"poolProvider": {"type": "string", "enum": ["Curve", "Balancer"]},
				"stability": {"type": "string", "enum": ["Stable", "Unstable", "Correlated", "Volatile"]},
				"stableBaseAsset": {"type": "string", "enum": [
					"USD",
					"EUR",
					"AUD",
					"CHF",
					"KRW",
					"GBP",
					"JPY",
					"CRV",
					"FTM",
					"Avax",
					"Ether",
					"Bitcoin",
					"Aave",
					"Link"
				]},
				"isAutomated": {"type": "boolean"}
			},
			"required": ["isPool", "stability", "isAutomated"],
			"allOf": [{
				"if": {"properties": {"isPool": {"const": true}}},
				"then": {"required": ["poolProvider"]}
			}, {
				"if": {"properties": {"stability": {"const": "Stable"}}},
				"then": {"required": ["stableBaseAsset"]}
			}, {
				"if": {"properties": {"stability": {"const": "Correlated"}}},
				"then": {"required": ["stableBaseAsset"]}
			}]
		}
	},
	"required": ["classification"]
}

=== yearn/ydaemon/data/meta/vaults/1/0x03eaE26089A8c28DDC4c81d65bEfE014C793A60d.json
{
  "$schema": "vault",
  "comment": "Curve frxETH-stETH-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 343,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve frxETH-stETH",
  "migrationAvailable": false,
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "Ether"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x9F8B5c0fc18B79DdFc05b21c43da7E324Cf3B8Eb.json
{
  "$schema": "vault",
  "comment": "Curve ibEUR-USDC-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 291,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve ibEUR-USDC",
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Volatile"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xf8768814b88281DE4F532a3beEfA5b85B69b9324.json
{
  "$schema": "vault",
  "comment": "Curve TUSD",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 37,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve TUSD",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xe92AE2cF5b373c1713eB5855D4D3aF81D8a8aCAE.json
{
  "$schema": "vault",
  "comment": "Curve Stax Frax Temple lp Vault",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 249,
  "migrationAvailable": false,
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve FraxTplLP",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Volatile"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xFBEB78a723b8087fD2ea7Ef1afEc93d35E8Bed42.json
{
  "$schema": "vault",
  "comment": "UNI",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 15,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "UNI",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Volatile"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x5B8C556B8b2a78696F0B9B830B3d67623122E270.json
{
  "$schema": "vault",
  "comment": "Curve stETH-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 266,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve stETH",
  "migrationAvailable": false,
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "Ether"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x84ca3Bf4822A342E9C1aD27bd5FBCf5fc5E37128.json
{
  "$schema": "vault",
  "comment": "yvBoost-yswap",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 212,
  "migrationAvailable": false,
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "yvBoost-yswap",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Correlated",
    "stableBaseAsset": "CRV"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x2E919d27D515868f3D5Bc9110fa738f9449FC6ad.json
{
  "$schema": "vault",
  "comment": "4.3 yveCRV vault",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 220,
  "migrationAvailable": false,
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve yveCRV Pool",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "CRV"
  }
}
