=== yearn/ydaemon/data/meta/_config/schema/vault.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "vault.json",
	"title": "Vault",
	"description": "A Yearn vault",
	"type": "object",
	"properties": {
		"comment": {
			"type": "string"
		},
		"hideAlways": {
			"type": "boolean"
		},
		"useVaultDataAsDefault": {
			"type": "boolean"
		},
		"depositsDisabled": {
			"type": "boolean"
		},
		"withdrawalsDisabled": {
			"type": "boolean"
		},
		"apyOverride": {
			"type": "number"
		},
		"apyTypeOverride": {
			"type": "string"
		},
		"order": {
			"type": "number"
		},
		"migrationAvailable": {
			"type": "boolean"
		},
		"allowZapIn": {
			"type": "boolean"
		},
		"allowZapOut": {
			"type": "boolean"
		},
		"zapInWith": {
			"type": "string"
		},
		"zapOutWith": {
			"type": "string"
		},
		"migrationContract": {
			"type": "string",
			"format": "address"
		},
		"migrationTargetVault": {
			"type": "string",
			"format": "address"
		},
		"retired": {
			"type": "boolean"
		},
		"displayName": {
			"type": "string"
		},
		"vaultIconOverride": {
			"type": "string"
		},
		"vaultSymbolOverride": {
			"type": "string"
		},
		"vaultNameOverride": {
			"type": "string"
		},
		"vaultDetailPageAssets": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"classification": {
			"type": "object",
			"properties": {
				"isPool": {"type": "boolean"},
				"poolProvider": {"type": "string", "enum": ["Curve", "Balancer"]},
				"stability": {"type": "string", "enum": ["Stable", "Unstable", "Correlated", "Volatile"]},
				"stableBaseAsset": {"type": "string", "enum": [
					"USD",
					"EUR",
					"AUD",
					"CHF",
					"KRW",
					"GBP",
					"JPY",
					"CRV",
					"FTM",
					"Avax",
					"Ether",
					"Bitcoin",
					"Aave",
					"Link"
				]},
				"isAutomated": {"type": "boolean"}
			},
			"required": ["isPool", "stability", "isAutomated"],
			"allOf": [{
				"if": {"properties": {"isPool": {"const": true}}},
				"then": {"required": ["poolProvider"]}
			}, {
				"if": {"properties": {"stability": {"const": "Stable"}}},
				"then": {"required": ["stableBaseAsset"]}
			}, {
				"if": {"properties": {"stability": {"const": "Correlated"}}},
				"then": {"required": ["stableBaseAsset"]}
			}]
		}
	},
	"required": ["classification"]
}

=== yearn/ydaemon/data/meta/vaults/1/0x5c0A86A32c129538D62C106Eb8115a8b02358d57.json
{
  "$schema": "vault",
  "comment": "Curve Rocket Pool",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 17,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve Rocket Pool",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "Ether"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xac333895ce1A73875CF7B4Ecdc5A743C12f3d82B.json
{
  "$schema": "vault",
  "comment": "3.1 weth vault",
  "hideAlways": false,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 226,
  "migrationAvailable": true,
  "migrationContract": "0x1824df8D751704FA10FA371d62A37f9B8772ab90",
  "migrationTargetVault": "0xa258C4606Ca8206D8aA700cE2143D7db854D168c",
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Weth",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Stable",
    "stableBaseAsset": "Ether"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xE22Ef63F2bD31eb69bF5917589a5daE3445c27b2.json
{
  "$schema": "vault",
  "comment": "4.3 Balancer Boosted Aave USD Pool",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 221,
  "migrationAvailable": false,
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Balancer Boosted Aave USD Pool",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Balancer",
    "stability": "Correlated",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x595a68a8c9D5C230001848B69b1947ee2A607164.json
{
  "$schema": "vault",
  "comment": "Curve ibGBP",
  "hideAlways": false,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 21.61,
  "migrationAvailable": true,
  "migrationContract": "0x9327e2FDc57c7d70782F29AB46F6385afaf4503C",
  "migrationTargetVault": "0xbE4afE6737CCf34cA21cdeF461E5C7547Adc8C77",
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve ibGBP",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "GBP"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x054AF22E1519b020516D72D749221c24756385C9.json
{
  "$schema": "vault",
  "comment": "Curve HUSD, this vault is tiny",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 31,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve HUSD",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x03c31f3444357087d5f568d24AE17f9177c8AA84.json
{
  "$schema": "vault",
  "comment": "Link 3.2 yVault",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 205,
  "migrationAvailable": false,
  "allowZapIn": false,
  "allowZapOut": false,
  "retired": true,
  "displayName": "Link",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Volatile"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x4856A7EFBbFcaE92AB13c5e2e322Fc77647bB856.json
{
  "$schema": "vault",
  "comment": "Ape 3.5 Rai Vault",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 215,
  "migrationAvailable": true,
  "migrationContract": "0x1824df8D751704FA10FA371d62A37f9B8772ab90",
  "migrationTargetVault": "0x873fB544277FD7b977B196a826459a69E27eA4ea",
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Rai",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Unstable"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x6B5ce31AF687a671a804d8070Ddda99Cab926dfE.json
{
  "$schema": "vault",
  "comment": "Curve ibGBP-USDC Pool yVault",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 91,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve ibGBP-USDC",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Volatile"
  }
}
