=== yearn/ydaemon/data/meta/_config/schema/vault.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "vault.json",
	"title": "Vault",
	"description": "A Yearn vault",
	"type": "object",
	"properties": {
		"comment": {
			"type": "string"
		},
		"hideAlways": {
			"type": "boolean"
		},
		"useVaultDataAsDefault": {
			"type": "boolean"
		},
		"depositsDisabled": {
			"type": "boolean"
		},
		"withdrawalsDisabled": {
			"type": "boolean"
		},
		"apyOverride": {
			"type": "number"
		},
		"apyTypeOverride": {
			"type": "string"
		},
		"order": {
			"type": "number"
		},
		"migrationAvailable": {
			"type": "boolean"
		},
		"allowZapIn": {
			"type": "boolean"
		},
		"allowZapOut": {
			"type": "boolean"
		},
		"zapInWith": {
			"type": "string"
		},
		"zapOutWith": {
			"type": "string"
		},
		"migrationContract": {
			"type": "string",
			"format": "address"
		},
		"migrationTargetVault": {
			"type": "string",
			"format": "address"
		},
		"retired": {
			"type": "boolean"
		},
		"displayName": {
			"type": "string"
		},
		"vaultIconOverride": {
			"type": "string"
		},
		"vaultSymbolOverride": {
			"type": "string"
		},
		"vaultNameOverride": {
			"type": "string"
		},
		"vaultDetailPageAssets": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"classification": {
			"type": "object",
			"properties": {
				"isPool": {"type": "boolean"},
				"poolProvider": {"type": "string", "enum": ["Curve", "Balancer"]},
				"stability": {"type": "string", "enum": ["Stable", "Unstable", "Correlated", "Volatile"]},
				"stableBaseAsset": {"type": "string", "enum": [
					"USD",
					"EUR",
					"AUD",
					"CHF",
					"KRW",
					"GBP",
					"JPY",
					"CRV",
					"FTM",
					"Avax",
					"Ether",
					"Bitcoin",
					"Aave",
					"Link"
				]},
				"isAutomated": {"type": "boolean"}
			},
			"required": ["isPool", "stability", "isAutomated"],
			"allOf": [{
				"if": {"properties": {"isPool": {"const": true}}},
				"then": {"required": ["poolProvider"]}
			}, {
				"if": {"properties": {"stability": {"const": "Stable"}}},
				"then": {"required": ["stableBaseAsset"]}
			}, {
				"if": {"properties": {"stability": {"const": "Correlated"}}},
				"then": {"required": ["stableBaseAsset"]}
			}]
		}
	},
	"required": ["classification"]
}

=== yearn/ydaemon/data/meta/vaults/1/0xB5dE7250128775a317B3f775a7AFcEC73571B732.json
{
  "$schema": "vault",
  "comment": "Curve sETH-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 274,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve sETH",
  "migrationAvailable": false,
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "Ether"
  }
}

=== yearn/ydaemon/data/meta/vaults/250/0xA97E7dA01C7047D6a65f894c99bE8c832227a8BC.json
{
  "$schema": "vault",
  "comment": "Curve MIM 3Pool",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 8,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve MIM 3Pool",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x2a38B9B0201Ca39B17B460eD2f11e4929559071E.json
{
  "$schema": "vault",
  "comment": "Curve GUSD",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 30,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve GUSD",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xA74d4B67b3368E83797a35382AFB776bAAE4F5C8.json
{
  "$schema": "vault",
  "comment": "Curve alUSD",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 25,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve alUSD",
  "migrationAvailable": true,
  "migrationContract": "0x9327e2fdc57c7d70782f29ab46f6385afaf4503c",
  "migrationTargetVault": "0x4CbB6A5EC00cEEC252a7091559484F7adb83165f",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "USD"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xa8eF50905352aCD611F53640b001E48F2eA31d63.json
{
  "$schema": "vault",
  "comment": "Curve cvxCRV-CRV-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 316,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve cvxCRV-CRV",
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "CRV"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xD347e7A3DdF5Ce4C42E19a4F30eEAA761795C72B.json
{
  "$schema": "vault",
  "comment": "Curve ibEUR-f",
  "hideAlways": false,
  "depositsDisabled": false,
  "withdrawalsDisabled": false,
  "order": 268,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": false,
  "displayName": "Curve ibEUR",
  "migrationAvailable": false,
  "classification": {
    "isAutomated": true,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Correlated",
    "stableBaseAsset": "EUR"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0xbD65955F752B2eF093B34B05e5FFb439AE8e5049.json
{
  "$schema": "vault",
  "comment": "4.2 Comp Vault",
  "hideAlways": true,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 245,
  "migrationAvailable": true,
  "migrationContract": "0x1824df8D751704FA10FA371d62A37f9B8772ab90",
  "migrationTargetVault": "0x4A3FE75762017DB0eD73a71C9A06db7768DB5e66",
  "allowZapIn": false,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Comp",
  "classification": {
    "isAutomated": false,
    "isPool": false,
    "stability": "Volatile"
  }
}

=== yearn/ydaemon/data/meta/vaults/1/0x8fA3A9ecd9EFb07A8CE90A6eb014CF3c0E3B32Ef.json
{
  "$schema": "vault",
  "comment": "Curve BBTC",
  "hideAlways": false,
  "depositsDisabled": true,
  "withdrawalsDisabled": false,
  "order": 49,
  "migrationAvailable": false,
  "allowZapIn": true,
  "allowZapOut": true,
  "retired": true,
  "displayName": "Curve BBTC",
  "classification": {
    "isAutomated": false,
    "isPool": true,
    "poolProvider": "Curve",
    "stability": "Stable",
    "stableBaseAsset": "Bitcoin"
  }
}
